In [2]:
# requests is linxu function for getting websites
import requests

In [3]:
r = requests.get('http://www.joburgmarket.co.za/dailyprices.php')

In [4]:
# print a portion of the files - top 200 characters
print(r.text[0:200])

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
	<title> Daily Prices |

In [5]:
# now that we have the file; use Beautifulsoup to read the file - resolve a file into its subsections
from bs4 import BeautifulSoup  

# if you reading from webpage
soup = BeautifulSoup(r.text, 'html.parser')

In [6]:
#This code searches the soup object for all td tags with the attribute class="tleft2". 
#It returns a special Beautiful Soup object (called a "ResultSet") containing the search results.

# Commodity is the name of the object being sold
commodity = soup.find_all('td', attrs={'class':'tleft2'})  

#values is the associated value
Values = soup.find_all('td', attrs={'class':'tleft'})

In [7]:
# list the first 3 items 
print(commodity[0:3])
print(len(commodity))
print(Values[0:3])
print(len(Values))

[<td class="tleft2" valign="top">AMADUMBE</td>, <td class="tleft2" valign="top">APPLES</td>, <td class="tleft2" valign="top">ASPARAGUS</td>]
174
[<td class="tleft" valign="top">R480.00<br/>MTD: R102,216.00</td>, <td class="tleft" valign="top">11<br/>MTD: 934</td>, <td class="tleft" valign="top">40<br/>MTD: 5,684</td>]
696

In [8]:
# create an empty records list
# loop through the records list and obtain the various text pieces that provide the name of the commodity
# update/append the name to the records list
records = []  
for i in range(0, len(commodity)):  
    commodity_name = commodity[i].text
    records.append((commodity_name))


# go through the values list and get the various quantities

# 1 . first we do it for the value sold piece
    
value_sold = []
for i in range(0, len(Values),4):
        # obtain the text portion of the value
        value_sold_1 = Values[i].text
        # clean up the text portion and remove any , commas;
        value_sold_2 = value_sold_1.replace(',','')
        value_sold_3 = value_sold_2.replace('R','')
        value_sold.append((value_sold_3))

        
# 2 . we do it for the volume sold piece
volume_sold = []
for i in range(1, len(Values),4):
        # obtain the text portion of the value
        volume_sold_1 = Values[i].text
        # clean up the text portion and remove any , commas
        volume_sold_2 = volume_sold_1.replace(',','')
        volume_sold.append((volume_sold_2))

#3. we do it for the KG sold piece
kg_sold = []
for i in range(2, len(Values),4):
        # obtain the text portion of the value
        kg_sold_1 = Values[i].text
        # clean up the text portion and remove any , commas
        kg_sold_2 = kg_sold_1.replace(',','')
        kg_sold.append((kg_sold_2))
        
#4. we do it for the Quantity avalible within the market
volume_avil = []
for i in range(3, len(Values),4):
        # obtain the text portion of the value
        volume_avil_1 = Values[i].text
        # clean up the text portion and remove any , commas; also store number as floating point
        volume_avil_2 = float(volume_avil_1.replace(',',''))
        volume_avil.append((volume_avil_2))

In [9]:
print("the number of items in the various tables:")
print("Name of produce:" + str(len(records)))
print("Value Sold Count:" + str(len(value_sold)))
print("volume Sold Count:" + str(len(volume_sold)))
print("KG Sold Count:" + str(len(kg_sold)))
print("Volume Avalible Count:" + str(len(volume_avil)))

the number of items in the various tables:
Name of produce:174
Value Sold Count:174
volume Sold Count:174
KG Sold Count:174
Volume Avalible Count:174

In [12]:
# split the value_sold list up
# it uses the 'MTD: ' as the seperator
# the first array [0] gives us the value for today
# the second array [1] gives us the MTD value
value_sold_TD = [i.split('MTD: ', 1)[0] for i in value_sold]
value_sold_MTD = [i.split('MTD: ', 1)[1] for i in value_sold]


# split the volume_sold list up
volume_sold_TD = [i.split('MTD: ', 1)[0] for i in volume_sold]
volume_sold_MTD = [i.split('MTD: ', 1)[1] for i in volume_sold]

# split the kg_sold list up
kg_sold_TD = [i.split('MTD: ', 1)[0] for i in kg_sold]
kg_sold_MTD = [i.split('MTD: ', 1)[1] for i in kg_sold]

In [13]:
# create a dataframe based on lists
import pandas as pd  
df = pd.DataFrame(data=list(zip(records,value_sold_TD,value_sold_MTD,volume_sold_TD,
                                volume_sold_MTD,kg_sold_TD,kg_sold_MTD,volume_avil)), 
                  columns=['Name', 'Value Sold (ZAR)', 'Value Sold (ZAR MTD)', 'Volume Sold',
                           'Volume sold (MTD)', 'KG Sold', 'KG Sold (MTD)','Volume Avalible'])

In [14]:
df

,Name,Value Sold (ZAR),Value Sold (ZAR MTD),Volume Sold,Volume sold (MTD),KG Sold,KG Sold (MTD),Volume Avalible
0,AMADUMBE,480.00,102216.00,11,934,40,5684,105.0
1,APPLES,1737943.00,36227564.00,18432,409947,231633,5335693,107976.0
2,ASPARAGUS,652.00,292723.00,5,787,25,3791,18.0
3,ATCHARA,26.32,972.72,1,34,1,34,68.0
4,AVOCADOS,714141.98,10607224.90,14883,170402,84846,1272993,13258.0
5,BABY BRINJALS,14250.00,94486.00,215,1857,858,7115,26.0
6,BABY BUTTERNUT,32674.00,269814.00,170,2433,747,10538,40.0
7,BABY CABBAGE,32550.00,316564.62,326,3492,1157,11486,60.0
8,BABY CARROTS,53252.00,470231.00,258,2366,1206,10985,69.0
9,BABY ENGLISH CUCUMBER,120.00,49890.00,2,1196,16,9568,5.0
10,BABY GEM SQUASH,8376.00,209646.00,49,2299,267,12366,5.0
11,BABY LEAF,4116.00,27068.00,41,250,41,250,0.0
12,BABY MARROWS,323436.00,3631573.10,2890,50836,12880,230371,2260.0
13,BABY MIX,1152.00,29009.00,10,290,50,1437,2.0
14,BABY SWEET CORN,8772.00,550242.00,43,3665,167,16577,33.0
15,BANANAS,1854063.00,44448109.50,14928,371166,249982,6527976,51630.0
16,BEAN SPROUTS,2944.00,42818.00,51,742,117,1728,21.0
17,BEANS,263383.87,4090094.98,8103,136473,33360,564612,3004.0
18,BEANS INDIAN,2460.00,27011.00,91,1042,231,2766,171.0
19,BEETROOT,425366.00,6736948.73,19965,388178,156869,2960236,50593.0
20,BLACKBERRIES,3360.00,35436.00,14,204,21,306,29.0
21,BOK CHOY PAK-CHOI,1100.00,5920.00,10,57,50,285,0.0
22,BRINJALS,60228.00,669197.44,1040,18135,4267,89141,112.0
23,BROCCOLI,106550.00,4908998.00,764,37334,2170,110578,237.0
24,BROCCOLI FLORETTES,5568.00,41832.00,28,338,67,811,0.0
25,BROCCOLI LEAVES,100.00,23670.00,3,591,24,4728,0.0
26,BRUSSELS SPROUTS,6400.00,40000.00,16,100,72,438,0.0
27,BUTTER LETTUCE,11206.00,103148.00,176,1564,541,4504,42.0
28,BUTTERNUT,482331.00,6781696.00,24886,335331,189956,2882173,27736.0
29,CABBAGE,552863.00,6864321.35,24021,350245,254551,3459269,4176.0
...,...,...,...,...,...,...,...,...
144,RED PEPPERS,393376.00,5485412.74,4881,71281,25121,361938,2244.0
145,RHUBARB,1880.00,34460.00,17,310,85,1550,20.0
146,ROCKET,3698.00,53738.00,90,1470,47,796,7.0
147,ROSEMARY,2261.00,18261.00,78,750,15,139,18.0
148,SAGE,135.00,2989.00,5,114,1,23,35.0
149,SALAD,504.00,5040.00,3,36,1,7,7.0
150,SATSUMAS,282544.00,3571710.00,11577,134021,33877,402140,38614.0
151,SHU-SHU,830.00,13265.00,20,173,80,692,20.0
152,SOUP GREENS,11592.00,213566.00,76,1454,465,9116,43.0
153,SPEARMINT,3555.00,76590.50,99,1828,132,3371,208.0
154,SPINACH,124048.80,2274818.71,6459,106640,31796,525198,4098.0
155,SPRING ONIONS,14360.00,248717.00,290,5015,951,17374,133.0
156,STARFRUIT(CARAMBOLA),2990.00,70570.00,15,290,30,580,177.0
157,STRAWBERRIES,63084.00,1467274.50,413,6351,1037,18771,309.0
158,SWEET BASIL,3438.00,29100.00,86,741,39,355,6.0
159,SWEET CORN,166580.00,2705131.00,853,26531,3542,87465,201.0
160,SWEET MELONS,82570.00,1569950.12,1740,32831,12186,236556,2870.0
161,SWEET POTATO,170554.00,4635043.74,3563,194462,43041,1430291,6257.0
162,TABLE CELERY,62150.00,736098.00,187,3070,1694,27564,1.0
163,THYME,590.00,10397.00,22,391,4,78,6.0
164,TOMATOES,4828438.68,74795605.00,178727,3315473,635198,10561939,25700.0
165,TOMATOES DRIED,260.00,8600.00,2,119,2,119,65.0
166,TURIA,140.00,8320.00,2,113,8,452,5.0
167,TURMERIC,1650.00,4000.00,3,9,15,45,88.0
168,TURNIP,2058.00,103177.83,50,2414,381,17252,115.0
169,VIRTUAL PRODUCT,0.00,0.00,0,0,0,0,602308.0
170,WATERCRESS,400.00,2065.00,20,111,4,22,7.0
171,WATERMELONS,341238.00,4354550.60,17812,191695,106912,1152746,13884.0
172,WILD ROCKET,415.00,2825.00,17,122,2,12,38.0
173,YELLOW PEPPERS,209942.00,3886377.06,1567,41872,7829,209336,494.0

Get the date of the last upload

In [15]:
#get the date of the last upload
soup.find_all('p')[1]

In [16]:
date = soup.find_all('p')[1].text

In [17]:
#import the regex function
import re

# get the first digit and print it the string
print("First digit in the string date is : " + re.search(r'\d+', date).group())
# get the start position of the string
print("First digit in the string date starts @ position : " + str(re.search(r'\d+', date).start()))

First digit in the string date is : 29
First digit in the string date starts @ position : 24

In [18]:
date_str = date[re.search(r'\d+', date).start():]
print(date_str)

29 March 2018

In [19]:
# convert string date to numeric python date

from datetime import datetime
from dateutil.parser import parse

In [20]:
parse(date_str)

datetime.datetime(2018, 3, 29, 0, 0)

In [21]:
# generate filename with leading zeros on month and date ie always 2 digits
fileout = str(parse(date_str).year) + str(parse(date_str).month).zfill(2)  + str(parse(date_str).day).zfill(2)

In [22]:
fileout

'20180329'

Write the dataframe to a text file with the correct date in the filename

In [23]:
import glob

In [24]:
# Give the filename you wish to save the file to
path = 'C:\\Users\\atish\Documents\\Web Scrapping\\Data\\' + fileout + '.txt'
print(path)

C:\Users\atish\Documents\Web Scrapping\Data\20180329.txt

In [25]:
#convert numbers to float in dataframe and not character - object
df.iloc[:,1::]=df.iloc[:,1::].astype(float)

In [26]:
# Use this function to search for any files which match your filename
files_present = glob.glob(path)

# if no matching files, write to csv, if there are matching files, print statement
if not files_present:
    df.to_csv(path , header=True, index=None, sep=',', mode='a')
else:
    print('WARNING: This file already exists!')

In [27]:
df['ZAR/KG']=df['Value Sold (ZAR MTD)']/df['KG Sold (MTD)']

In [29]:
df.sort_values(by='ZAR/KG', ascending=False)

,Name,Value Sold (ZAR),Value Sold (ZAR MTD),Volume Sold,Volume sold (MTD),KG Sold,KG Sold (MTD),Volume Avalible,ZAR/KG
40,CHILLIES PROCESSED,0.0,2.700000e+01,0.0,1.0,0.0,0.0,7.0,inf
149,SALAD,504.0,5.040000e+03,3.0,36.0,1.0,7.0,7.0,720.000000
111,OREGANO,540.0,4.340000e+03,20.0,163.0,2.0,16.0,0.0,271.250000
172,WILD ROCKET,415.0,2.825000e+03,17.0,122.0,2.0,12.0,38.0,235.416667
42,CHIVES,610.0,4.777000e+03,28.0,210.0,3.0,21.0,19.0,227.476190
163,THYME,590.0,1.039700e+04,22.0,391.0,4.0,78.0,6.0,133.294872
147,ROSEMARY,2261.0,1.826100e+04,78.0,750.0,15.0,139.0,18.0,131.374101
148,SAGE,135.0,2.989000e+03,5.0,114.0,1.0,23.0,35.0,129.956522
156,STARFRUIT(CARAMBOLA),2990.0,7.057000e+04,15.0,290.0,30.0,580.0,177.0,121.672414
51,CURRY LEAVES,515.0,4.351062e+04,22.0,2011.0,4.0,371.0,11.0,117.279299
68,GINGER PROCESSED,0.0,1.636620e+03,0.0,8.0,0.0,14.0,25.0,116.901429
20,BLACKBERRIES,3360.0,3.543600e+04,14.0,204.0,21.0,306.0,29.0,115.803922
11,BABY LEAF,4116.0,2.706800e+04,41.0,250.0,41.0,250.0,0.0,108.272000
142,RASPBERRIES,24580.0,4.213740e+05,218.0,3577.0,260.0,4295.0,113.0,98.108033
97,MICRO HERBS,400.0,5.360000e+03,20.0,273.0,4.0,55.0,0.0,97.454545
170,WATERCRESS,400.0,2.065000e+03,20.0,111.0,4.0,22.0,7.0,93.863636
57,EDIBLE FLOWERS,580.0,1.850000e+03,29.0,98.0,6.0,20.0,1.0,92.500000
26,BRUSSELS SPROUTS,6400.0,4.000000e+04,16.0,100.0,72.0,438.0,0.0,91.324201
167,TURMERIC,1650.0,4.000000e+03,3.0,9.0,15.0,45.0,88.0,88.888889
158,SWEET BASIL,3438.0,2.910000e+04,86.0,741.0,39.0,355.0,6.0,81.971831
157,STRAWBERRIES,63084.0,1.467274e+06,413.0,6351.0,1037.0,18771.0,309.0,78.167093
2,ASPARAGUS,652.0,2.927230e+05,5.0,787.0,25.0,3791.0,18.0,77.215247
87,LEMON GRASS,320.0,3.261000e+03,17.0,219.0,3.0,44.0,57.0,74.113636
165,TOMATOES DRIED,260.0,8.600000e+03,2.0,119.0,2.0,119.0,65.0,72.268908
124,PECAN NUT (SHELL),280.0,6.281000e+04,1.0,222.0,4.0,885.0,364.0,70.971751
138,RADICCHIO,900.0,5.250000e+03,60.0,370.0,12.0,74.0,0.0,70.945946
146,ROCKET,3698.0,5.373800e+04,90.0,1470.0,47.0,796.0,7.0,67.510050
101,MUSHROOMS,68531.0,9.735050e+05,273.0,3823.0,1013.0,14423.0,302.0,67.496707
48,CORIANDER/DHANYA,345.0,7.209000e+03,12.0,606.0,44.0,111.0,94.0,64.945946
70,GOOSEBERRIES,8930.0,1.733000e+05,27.0,665.0,92.0,2696.0,77.0,64.280415
...,...,...,...,...,...,...,...,...,...
160,SWEET MELONS,82570.0,1.569950e+06,1740.0,32831.0,12186.0,236556.0,2870.0,6.636695
110,ORANGES,540440.0,7.424230e+06,18001.0,167781.0,116954.0,1191104.0,98925.0,6.233066
168,TURNIP,2058.0,1.031778e+05,50.0,2414.0,381.0,17252.0,115.0,5.980630
112,PAMPALMOESE,35055.0,3.434040e+05,430.0,7686.0,5375.0,57968.0,2763.0,5.924027
126,PINEAPPLES,265945.0,5.771501e+06,7541.0,128698.0,59920.0,990796.0,0.0,5.825115
122,PEARS,406262.0,9.194381e+06,7530.0,155115.0,78454.0,1614005.0,30330.0,5.696625
76,GREEN PEPPERS,699742.0,9.053012e+06,24100.0,328874.0,121568.0,1652979.0,4901.0,5.476786
9,BABY ENGLISH CUCUMBER,120.0,4.989000e+04,2.0,1196.0,16.0,9568.0,5.0,5.214256
92,LIQUIDS,682.0,4.464000e+03,11.0,72.0,132.0,864.0,236.0,5.166667
25,BROCCOLI LEAVES,100.0,2.367000e+04,3.0,591.0,24.0,4728.0,0.0,5.006345
108,ONIONS,4156953.0,8.704946e+07,112228.0,2117112.0,1014070.0,19068486.0,181562.0,4.565096
75,GREEN MEALIES,7580.0,1.146740e+05,120.0,1572.0,1554.0,25399.0,55.0,4.514902
32,CARROTS,1819579.5,2.442015e+07,48127.0,718739.0,354821.0,5582206.0,12914.0,4.374641
154,SPINACH,124048.8,2.274819e+06,6459.0,106640.0,31796.0,525198.0,4098.0,4.331354
127,PIQUANT PEPPERS (PEPPER DEW),60.0,3.350000e+02,4.0,26.0,12.0,78.0,30.0,4.294872
66,GEM SQUASHES,131139.0,2.291635e+06,3987.0,73396.0,30421.0,556617.0,1020.0,4.117077
93,MAIZE MEAL,0.0,1.490000e+03,0.0,15.0,0.0,375.0,59.0,3.973333
171,WATERMELONS,341238.0,4.354551e+06,17812.0,191695.0,106912.0,1152746.0,13884.0,3.777546
132,POTATOES,10574576.0,1.290777e+08,228135.0,3663387.0,2235475.0,35693003.0,20166.0,3.616332
161,SWEET POTATO,170554.0,4.635044e+06,3563.0,194462.0,43041.0,1430291.0,6257.0,3.240630
28,BUTTERNUT,482331.0,6.781696e+06,24886.0,335331.0,189956.0,2882173.0,27736.0,2.352980
19,BEETROOT,425366.0,6.736949e+06,19965.0,388178.0,156869.0,2960236.0,50593.0,2.275815
29,CABBAGE,552863.0,6.864321e+06,24021.0,350245.0,254551.0,3459269.0,4176.0,1.984327
79,HUBBARD SQUASHES,196145.0,3.279007e+06,4183.0,54012.0,133856.0,1728384.0,1414.0,1.897152
136,PUMPKINS GOURMET GLOBE,0.0,8.100000e+02,0.0,135.0,0.0,675.0,205.0,1.200000
135,PUMPKINS,34138.0,9.057910e+05,878.0,22995.0,29852.0,781830.0,939.0,1.158552
128,PKS BLUE QUEEN,85710.0,1.817276e+06,2174.0,45207.0,76090.0,1582245.0,6048.0,1.148543
37,CHESTNUTS,0.0,0.000000e+00,0.0,0.0,0.0,0.0,4.0,NaN
44,CLEMENTINES,0.0,0.000000e+00,0.0,0.0,0.0,0.0,360.0,NaN
169,VIRTUAL PRODUCT,0.0,0.000000e+00,0.0,0.0,0.0,0.0,602308.0,NaN